import { ContentItem, Template } from "./types";

export const mockContents: ContentItem[] = [
  {
    id: "1",
    title: "성주참외 신상품 오픈 — 올해 첫 출하",
    templateType: "new_product",
    productName: "성주참외 1.5kg",
    category: "참외",
    coreMessage:
      "당도 높고 아삭한 식감, 올해 첫 출하 성주참외를 산물 회원에게 먼저 소개합니다",
    supportPoints: [
      "국내 최대 참외 산지 성주산 인증",
      "당도 13브릭스 이상 선별",
      "냉장 새벽배송으로 신선하게",
    ],
    audience: "달콤하고 아삭한 제철 과일을 즐기는 30~50대 주부",
    hook: "올해 첫 성주참외, 산물 회원에게 가장 먼저 소개합니다",
    cta: "지금 주문하기",
    link: "https://sanmul.kr/products/chamoe-2024",
    scheduledDate: "2026-04-16",
    status: "scheduled",
    platforms: ["blog", "instagram", "threads", "openchat"],
    channelDrafts: {
      blog: `# 올해 첫 성주참외, 산물이 먼저 소개합니다\n\n봄이 되면 가장 먼저 생각나는 과일이 있다면, 바로 참외일 것입니다.\n그 중에서도 성주참외는 국내 참외 생산량의 70% 이상을 담당하는 명실상부한 참외의 본고장입니다.\n\n## 왜 성주참외인가요?\n\n성주참외는 단순히 유명하기 때문에 소개하는 것이 아닙니다. 산물이 기준으로 삼는 것은 항상 **맛과 만족도**입니다.\n\n- **당도 13브릭스 이상 선별**: 일반 마트 참외보다 확연히 다른 단맛\n- **국내 최대 참외 산지 인증**: 신뢰할 수 있는 생산 이력\n- **냉장 새벽배송**: 받는 순간부터 신선함 유지\n\n## 추천 드리는 분\n\n달콤하고 아삭한 제철 과일을 즐기시는 분, 가족들과 함께 봄의 맛을 즐기고 싶으신 30~50대 주부님들께 특히 추천드립니다.\n\n지금 주문하기 → https://sanmul.kr/products/chamoe-2024`,
      instagram: `✨ 올해 첫 성주참외, 산물 회원에게 가장 먼저 소개합니다\n\n🍈 당도 13브릭스 이상 선별\n🍈 성주 인증 농가 직수급\n🍈 냉장 새벽배송\n\n봄에 가장 먼저 챙겨야 할 제철 과일.\n달콤하고 아삭한 성주참외, 지금 확인해보세요.\n\n👇 주문 링크는 프로필 링크에서\n\n#성주참외 #제철과일 #산물 #신선과일 #참외맛집 #봄과일`,
      threads: `올해 첫 성주참외 나왔어요 🍈\n\n보통 마트에서 파는 것보다 당도가 확실히 달라요.\n산물에서 당도 13브릭스 이상만 따로 골라서 소개하거든요.\n\n제철에 맞는 과일을 제때 먹는 게 제일 맛있는 법.\n링크는 프로필에 있어요 👆`,
      openchat: `🍈 [산물 회원 선공개] 올해 첫 성주참외 오픈\n\n안녕하세요, 산물입니다.\n이번 주 산물 회원 여러분께 가장 먼저 소개드릴 새 상품이 도착했습니다.\n\n📌 상품: 성주참외 1.5kg\n📌 특징: 당도 13브릭스 이상, 성주 인증 농가 선별\n📌 배송: 냉장 새벽배송\n\n🔗 주문 링크: https://sanmul.kr/products/chamoe-2024\n\n회원 여러분께 항상 좋은 과일을 가장 먼저 소개드릴 수 있어서 기쁩니다. 🙏`,
    },
    createdAt: "2026-04-10",
    updatedAt: "2026-04-14",
  },
  {
    id: "2",
    title: "가정용 실속형 참외 구매 후기 공유",
    templateType: "review",
    productName: "가정용 참외 3kg",
    category: "참외",
    coreMessage:
      "실제 구매 고객 후기를 통해 산물 참외의 맛과 배송 만족도를 확인하세요",
    supportPoints: [
      "재구매율 83% 이상",
      "아이 간식으로 딱 좋다는 반응",
      "배송 신선도에 높은 만족",
    ],
    audience: "믿을 수 있는 과일 쇼핑몰을 찾고 있는 주부",
    hook: "첫 구매 후 바로 재구매한 분들이 이렇게 말했어요",
    cta: "후기 더 보기",
    link: "https://sanmul.kr/reviews/chamoe",
    scheduledDate: "2026-04-19",
    status: "review",
    platforms: ["instagram", "threads", "blog"],
    channelDrafts: {
      blog: `# 산물 참외, 실제 구매 고객들은 어떻게 생각할까요?\n\n좋은 과일을 소개하는 것도 중요하지만, 실제로 드셔본 분들의 이야기가 가장 솔직합니다.\n\n## 고객 후기 모음\n\n**"처음엔 반신반의했는데 정말 달아요"**\n마트에서 사던 참외랑 차원이 달랐어요. 아이들이 너무 좋아해서 이틀 만에 다 먹었어요 — 40대 주부\n\n**"배송이 빨라서 신선하게 받았어요"**\n새벽배송이라 아침에 냉장고에서 꺼내서 바로 먹을 수 있었어요. 재구매 확정입니다 — 35세 주부\n\n산물의 재구매율은 83%입니다. 처음 오신 분들도 두 번 세 번 찾아오는 이유가 있습니다.\n\n→ 후기 더 보기: https://sanmul.kr/reviews/chamoe`,
      instagram: `💬 "마트 참외랑 차원이 달랐어요"\n\n실제 구매하신 분들이 이렇게 말씀해 주셨어요.\n\n✔️ 재구매율 83%\n✔️ 아이 간식으로 딱!\n✔️ 새벽배송 신선도 최고\n\n처음 주문하신 분들이 두 번 세 번 찾아오는 이유, 직접 확인해보세요.\n\n#산물후기 #참외추천 #제철과일 #신선배송`,
      threads: `산물 참외 후기 모아봤어요 📝\n\n재구매율이 83%래요. 한 번 먹어본 분들이 계속 찾는다는 거잖아요.\n\n특히 아이 있는 집에서 반응이 좋더라고요.\n달콤하고 아삭해서 과자보다 낫다고 🍈`,
    },
    createdAt: "2026-04-11",
    updatedAt: "2026-04-13",
  },
  {
    id: "3",
    title: "선물용 과일 고르는 법 — 만족도 높은 선물 가이드",
    templateType: "info",
    productName: "선물세트 시리즈",
    category: "선물세트",
    coreMessage:
      "가격보다 만족도 높은 과일 선물을 고르는 기준을 알려드립니다",
    supportPoints: [
      "과일 선물의 흔한 실패 패턴",
      "받는 사람이 진짜 좋아하는 과일 선물 기준",
      "산물이 선물세트를 구성하는 방식",
    ],
    audience: "부모님 또는 지인에게 과일 선물을 고민 중인 30~50대",
    hook: "선물용 과일, 비싸다고 다 좋은 건 아닙니다",
    cta: "산물 선물세트 보러가기",
    link: "https://sanmul.kr/gift",
    scheduledDate: "2026-04-22",
    status: "drafting",
    platforms: ["blog", "instagram", "threads"],
    channelDrafts: {
      blog: `# 선물용 과일 고를 때 꼭 알아야 할 것들\n\n"비싼 과일 선물 세트인데 왜 맛이 없지?"\n\n이런 경험, 한 번쯤 있으실 겁니다. 선물용 과일은 단순히 브랜드나 가격만 보면 실패할 수 있어요.\n\n## 과일 선물의 흔한 실패 패턴\n\n1. 포장은 화려한데 과일은 평범한 경우\n2. 당도 표시가 없거나 모호한 경우\n3. 배송 중 물러짐 처리 미흡\n\n## 산물이 선물세트를 구성하는 방식\n\n산물은 선물세트를 구성할 때 **받는 사람의 만족도**를 가장 먼저 생각합니다.\n\n- 당도 기준 통과 상품만 포함\n- 손상 방지 포장\n- 카드 메시지 서비스\n\n→ 산물 선물세트 보러가기: https://sanmul.kr/gift`,
      instagram: `🎁 선물용 과일, 비싸다고 다 좋은 건 아닙니다\n\n포장만 화려하고 맛이 없으면 의미 없잖아요.\n\n산물 선물세트의 기준:\n✔️ 당도 검증 통과 상품만\n✔️ 손상 방지 포장\n✔️ 받는 분이 진짜 좋아하는 맛\n\n부모님, 지인께 드릴 선물 고민이라면 👇\n프로필 링크에서 확인해보세요.\n\n#과일선물 #선물세트 #산물 #부모님선물`,
      threads: `선물용 과일 고를 때 저는 이걸 봐요 🎁\n\n포장보다 당도.\n브랜드보다 실제 맛.\n\n그래서 선물세트도 맛 기준으로 먼저 고르고,\n포장은 그 다음에 고려해요.\n\n산물 선물세트 링크 프로필에 올려뒀어요 👆`,
    },
    createdAt: "2026-04-12",
    updatedAt: "2026-04-12",
  },
  {
    id: "4",
    title: "시즌 막바지 — 한라봉 마지막 입고 안내",
    templateType: "season_end",
    productName: "제주 한라봉 2kg",
    category: "감귤류",
    coreMessage:
      "이번 시즌 마지막 한라봉입니다. 제주 한라봉의 제철 맛을 놓치지 마세요",
    supportPoints: [
      "이번 시즌 마지막 입고",
      "껍질이 얇고 과즙이 풍부한 제주 한라봉",
      "소량 한정 판매",
    ],
    audience: "제철 과일을 제때 즐기는 것을 중요시하는 주부",
    hook: "이번 시즌 한라봉, 이번이 마지막입니다",
    cta: "지금 바로 주문하기",
    link: "https://sanmul.kr/products/hallabong-last",
    scheduledDate: "2026-04-15",
    status: "scheduled",
    platforms: ["instagram", "openchat", "threads"],
    channelDrafts: {
      instagram: `🍊 이번 시즌 한라봉, 이번이 마지막입니다\n\n제주 한라봉의 제철은 짧습니다.\n이번 입고분이 올해 마지막이에요.\n\n🍊 껍질이 얇고 과즙이 풍부\n🍊 소량 한정\n🍊 지금 아니면 내년에\n\n후회하지 말고 지금 주문하세요 👇\n\n#한라봉 #제주한라봉 #시즌마감 #산물 #제철과일`,
      threads: `제주 한라봉 마지막 입고예요 🍊\n\n올해 시즌이 끝나가고 있어요.\n이번 입고분 다 팔리면 내년까지 없어요.\n\n껍질 얇고 과즙 진한 거 좋아하시면 지금이 마지막 기회 🙏`,
      openchat: `🍊 [긴급 안내] 제주 한라봉 시즌 마지막 입고\n\n산물 회원 여러분,\n이번 시즌 제주 한라봉 마지막 입고 소식을 가장 먼저 전해드립니다.\n\n📌 상품: 제주 한라봉 2kg\n📌 수량: 소량 한정\n📌 특이사항: 이번 입고 후 올해 시즌 종료\n\n🔗 주문 링크: https://sanmul.kr/products/hallabong-last\n\n재고 소진 시 조기 마감될 수 있습니다. 서둘러 주세요! 🙏`,
    },
    createdAt: "2026-04-13",
    updatedAt: "2026-04-14",
  },
  {
    id: "5",
    title: "산물 회원 전용 — 딸기 선공개 혜택",
    templateType: "member_benefit",
    productName: "논산 설향딸기 500g x 2팩",
    category: "딸기",
    coreMessage:
      "산물 오픈채팅 회원에게만 먼저 소개하는 논산 설향딸기 신상품",
    supportPoints: [
      "회원 전용 오픈 24시간 전 선공개",
      "회원 한정 첫 주문 할인",
      "재고 한정으로 일반 오픈 전 마감 가능",
    ],
    audience: "산물 오픈채팅 회원, 딸기를 즐겨 드시는 주부",
    hook: "산물 회원에게만 먼저 알려드립니다",
    cta: "회원 전용 링크로 주문하기",
    link: "https://sanmul.kr/members/strawberry-early",
    scheduledDate: "2026-04-17",
    status: "review",
    platforms: ["openchat", "instagram"],
    channelDrafts: {
      openchat: `🍓 [회원 전용 선공개] 논산 설향딸기 오픈\n\n안녕하세요, 산물입니다.\n오늘은 일반 오픈 전 산물 회원 여러분께 먼저 소개드립니다.\n\n📌 상품: 논산 설향딸기 500g x 2팩\n📌 특징: 향이 진하고 당도 높은 논산 대표 딸기 품종\n📌 회원 혜택: 일반 공개 24시간 전 선구매 가능\n\n⚠️ 회원 전용 링크로만 주문 가능하며, 재고 소진 시 종료됩니다.\n\n🔗 회원 전용 링크: https://sanmul.kr/members/strawberry-early\n\n항상 좋은 과일을 가장 먼저 드릴 수 있어서 감사합니다 🙏`,
      instagram: `🍓 이번 주 신상품은 논산 설향딸기예요\n\n향이 진하고 당도가 높은 논산 대표 딸기 품종.\n산물에서 엄선한 이번 시즌 딸기를 소개합니다.\n\n✔️ 논산 설향딸기\n✔️ 500g x 2팩 구성\n✔️ 당일 수확 당일 발송\n\n주문 링크는 프로필에서 👆\n\n#설향딸기 #논산딸기 #딸기 #산물 #신선과일`,
    },
    createdAt: "2026-04-14",
    updatedAt: "2026-04-14",
  },
  {
    id: "6",
    title: "재구매 고객을 위한 감사 콘텐츠 — 복숭아 추천",
    templateType: "repurchase",
    productName: "천도복숭아 1.5kg",
    category: "복숭아",
    coreMessage:
      "한 번 구매 후 또 찾아주신 분들을 위한 이번 시즌 복숭아 추천",
    supportPoints: [
      "재구매 고객을 위한 감사 안내",
      "6월 제철 천도복숭아 미리 예약 가능",
      "재구매 고객 전용 구성",
    ],
    audience: "산물에서 한 번 이상 구매하신 고객",
    hook: "다시 찾아와 주셔서 감사합니다 — 이번에도 좋은 과일로 보답할게요",
    cta: "이번 시즌 복숭아 미리 예약하기",
    link: "https://sanmul.kr/pre-order/peach",
    scheduledDate: "2026-04-24",
    status: "idea",
    platforms: ["openchat", "instagram", "blog"],
    channelDrafts: {},
    createdAt: "2026-04-14",
    updatedAt: "2026-04-14",
  },
  {
    id: "7",
    title: "마트 딸기 vs 산물 딸기 — 차이를 알아볼까요",
    templateType: "comparison",
    productName: "논산 설향딸기",
    category: "딸기",
    coreMessage:
      "같은 딸기라도 선별 기준과 배송 방식에 따라 맛이 달라집니다",
    supportPoints: [
      "당도 기준 비교",
      "배송 환경 차이",
      "선별 과정의 차이",
    ],
    audience: "마트 과일에 실망한 경험이 있는 주부",
    hook: "마트에서 산 딸기가 왜 맛없었는지 알게 됐어요",
    cta: "산물 딸기 확인하기",
    link: "https://sanmul.kr/products/strawberry",
    scheduledDate: "2026-04-20",
    status: "drafting",
    platforms: ["blog", "instagram", "threads"],
    channelDrafts: {
      blog: `# 마트 딸기 vs 산물 딸기, 무엇이 다를까요?\n\n같은 딸기인데 왜 맛이 다를까요?\n많은 분들이 "딸기가 그냥 딸기지" 라고 생각하시지만, 실제로는 여러 요소가 맛에 영향을 미칩니다.\n\n## 1. 당도 선별 기준의 차이\n\n마트 딸기는 외관(크기, 색상) 위주로 선별되는 경우가 많습니다.\n산물은 당도를 기준으로 선별합니다.\n\n## 2. 배송 환경\n\n상온 배송과 냉장 배송은 받았을 때 신선도에 큰 차이를 만듭니다.\n\n## 3. 선별 과정\n\n소량씩 꼼꼼하게 선별하는 것과 대량으로 유통되는 것의 차이.\n\n산물이 조금 더 비쌀 수 있지만, 그 차이가 맛으로 느껴집니다.\n\n→ 산물 딸기 확인하기: https://sanmul.kr/products/strawberry`,
      instagram: `🍓 마트 딸기가 왜 맛없었는지 알게 됐어요\n\n외관 선별 vs 당도 선별\n상온 배송 vs 냉장 새벽배송\n대량 유통 vs 소량 선별\n\n같은 딸기라도 이런 차이가 있어요.\n\n산물은 맛 기준으로만 골라요 🍓\n\n#딸기 #산물딸기 #신선과일 #마트vs온라인`,
      threads: `마트 딸기 실망한 적 있으세요? 🍓\n\n저도 그랬어요. 근데 이유가 있더라고요.\n\n마트는 외관 중심 선별,\n산물은 당도 기준 선별.\n\n그 차이가 입에서 느껴져요 😊`,
    },
    createdAt: "2026-04-09",
    updatedAt: "2026-04-11",
  },
  {
    id: "8",
    title: "돌발특가 — 수박 한정 특가 오픈",
    templateType: "flash_offer",
    productName: "국내산 수박 6~7kg",
    category: "수박",
    coreMessage: "예상치 못한 좋은 수박이 들어왔습니다. 회원 한정 특가로 소개합니다",
    supportPoints: [
      "당도 높은 수박 소량 입고",
      "회원 전용 특가 가격",
      "오늘 마감 예정",
    ],
    audience: "여름 수박을 즐기는 가족 단위 주부",
    hook: "갑자기 좋은 수박이 들어왔어요 — 오늘만 특가",
    cta: "지금 바로 주문하기",
    link: "https://sanmul.kr/flash/watermelon",
    scheduledDate: "2026-04-18",
    status: "idea",
    platforms: ["openchat", "instagram"],
    channelDrafts: {},
    createdAt: "2026-04-14",
    updatedAt: "2026-04-14",
  },
];

export const mockTemplates: Template[] = [
  {
    id: "t1",
    name: "신상품 오픈형",
    type: "new_product",
    description: "새로운 상품을 처음 소개할 때 사용하는 템플릿",
    purpose: "신상품 런칭, 시즌 첫 상품 안내",
    blogTemplate: `# {{hook}}\n\n{{coreMessage}}\n\n## 왜 {{productName}}인가요?\n\n{{supportPoint1}}\n{{supportPoint2}}\n{{supportPoint3}}\n\n## 추천 드리는 분\n\n{{audience}}\n\n{{cta}} → {{link}}`,
    instagramTemplate: `✨ {{hook}}\n\n🍃 {{supportPoint1}}\n🍃 {{supportPoint2}}\n🍃 {{supportPoint3}}\n\n{{coreMessage}}\n\n👇 주문 링크는 프로필 링크에서\n\n#산물 #신선과일 #{{productName}}`,
    threadsTemplate: `{{hook}} 🌿\n\n{{coreMessage}}\n\n특히 {{audience}}에게 추천드려요.\n링크는 프로필에 있어요 👆`,
    tiktokTemplate: `[훅] {{hook}}\n\n[핵심1] {{supportPoint1}}\n[핵심2] {{supportPoint2}}\n\n[마무리] {{cta}}! 링크는 프로필에서 확인하세요.`,
    openchatTemplate: `🌿 [산물 회원 선공개] {{productName}} 오픈\n\n안녕하세요, 산물입니다.\n\n📌 상품: {{productName}}\n📌 특징: {{coreMessage}}\n📌 추천 대상: {{audience}}\n\n🔗 {{cta}}: {{link}}\n\n회원 여러분께 항상 좋은 과일을 가장 먼저 소개드릴 수 있어서 기쁩니다. 🙏`,
    usageCount: 12,
  },
  {
    id: "t2",
    name: "후기 공유형",
    type: "review",
    description: "실제 구매 고객의 후기를 활용한 신뢰 콘텐츠",
    purpose: "사회적 증거 형성, 구매 망설임 해소",
    blogTemplate: `# {{productName}}, 실제 구매 고객들은 어떻게 생각할까요?\n\n{{hook}}\n\n## 고객 후기 모음\n\n{{coreMessage}}\n\n{{supportPoint1}}\n{{supportPoint2}}\n{{supportPoint3}}\n\n{{cta}} → {{link}}`,
    instagramTemplate: `💬 "{{hook}}"\n\n실제 구매하신 분들이 이렇게 말씀해 주셨어요.\n\n✔️ {{supportPoint1}}\n✔️ {{supportPoint2}}\n✔️ {{supportPoint3}}\n\n{{cta}} 👇\n\n#산물후기 #{{productName}} #신선과일`,
    threadsTemplate: `{{productName}} 후기 모아봤어요 📝\n\n{{coreMessage}}\n\n특히 {{supportPoint1}}\n링크 프로필에 있어요 👆`,
    tiktokTemplate: `[훅] {{hook}}\n\n[후기1] {{supportPoint1}}\n[후기2] {{supportPoint2}}\n\n[CTA] {{cta}}! 링크는 프로필에서.`,
    openchatTemplate: `📝 [회원 후기 공유] {{productName}}\n\n안녕하세요, 산물입니다.\n\n구매해주신 회원분들의 솔직한 후기를 공유드립니다.\n\n💬 {{coreMessage}}\n\n✔️ {{supportPoint1}}\n✔️ {{supportPoint2}}\n\n🔗 {{cta}}: {{link}}\n\n항상 만족스러운 과일로 보답하겠습니다 🙏`,
    usageCount: 8,
  },
  {
    id: "t3",
    name: "정보형",
    type: "info",
    description: "과일 관련 유용한 정보를 제공하는 콘텐츠",
    purpose: "전문성 구축, 팔로워 유입, SEO",
    blogTemplate: `# {{hook}}\n\n{{coreMessage}}\n\n## {{supportPoint1}}\n\n## {{supportPoint2}}\n\n## {{supportPoint3}}\n\n{{audience}}에게 특히 도움이 됩니다.\n\n{{cta}} → {{link}}`,
    instagramTemplate: `📌 {{hook}}\n\n{{coreMessage}}\n\n💡 {{supportPoint1}}\n💡 {{supportPoint2}}\n💡 {{supportPoint3}}\n\n{{audience}}에게 추천드려요!\n\n#과일정보 #산물 #신선과일`,
    threadsTemplate: `{{hook}} 🤔\n\n{{coreMessage}}\n\n알아두면 좋은 정보예요!\n링크 프로필에 있어요 👆`,
    tiktokTemplate: `[훅] {{hook}}\n\n[정보1] {{supportPoint1}}\n[정보2] {{supportPoint2}}\n\n[CTA] 더 알고 싶으면 링크 확인!`,
    openchatTemplate: `📚 [산물 정보] {{productName}} 관련 정보\n\n안녕하세요, 산물입니다.\n\n{{hook}}\n\n{{coreMessage}}\n\n📌 {{supportPoint1}}\n📌 {{supportPoint2}}\n\n🔗 더 자세한 내용: {{link}}`,
    usageCount: 5,
  },
  {
    id: "t4",
    name: "비교형",
    type: "comparison",
    description: "산물 상품과 일반 상품의 차이를 보여주는 콘텐츠",
    purpose: "차별화 강조, 가격 정당화",
    blogTemplate: `# {{hook}}\n\n{{coreMessage}}\n\n## 차이점 1: {{supportPoint1}}\n\n## 차이점 2: {{supportPoint2}}\n\n## 차이점 3: {{supportPoint3}}\n\n{{audience}}라면 이 차이를 직접 느껴보세요.\n\n{{cta}} → {{link}}`,
    instagramTemplate: `🆚 {{hook}}\n\n{{supportPoint1}}\n{{supportPoint2}}\n{{supportPoint3}}\n\n{{coreMessage}}\n\n{{cta}} 👇\n\n#산물 #과일비교 #신선과일`,
    threadsTemplate: `{{hook}} 🆚\n\n{{coreMessage}}\n\n진짜 차이는 맛으로 느껴봐야 알아요.\n링크 프로필에 있어요 👆`,
    tiktokTemplate: `[훅] {{hook}}\n\n[비교1] {{supportPoint1}}\n[비교2] {{supportPoint2}}\n\n[CTA] 차이를 직접 확인하세요!`,
    openchatTemplate: `🆚 [산물 vs 일반] {{productName}} 비교\n\n{{hook}}\n\n{{coreMessage}}\n\n📌 {{supportPoint1}}\n📌 {{supportPoint2}}\n\n🔗 {{cta}}: {{link}}`,
    usageCount: 3,
  },
  {
    id: "t5",
    name: "회원 혜택형",
    type: "member_benefit",
    description: "오픈채팅 회원에게만 제공되는 혜택 안내",
    purpose: "회원 충성도 강화, 오픈채팅 가입 유도",
    blogTemplate: `# 산물 회원이 되면 받을 수 있는 혜택\n\n{{hook}}\n\n{{coreMessage}}\n\n## 회원 전용 혜택\n\n{{supportPoint1}}\n{{supportPoint2}}\n{{supportPoint3}}\n\n{{audience}}라면 지금 바로 회원이 되어보세요.\n\n{{cta}} → {{link}}`,
    instagramTemplate: `🌿 {{hook}}\n\n산물 회원만의 특별한 혜택:\n✔️ {{supportPoint1}}\n✔️ {{supportPoint2}}\n✔️ {{supportPoint3}}\n\n{{cta}} 👇\n\n#산물회원 #산물오픈채팅 #과일구독`,
    threadsTemplate: `{{hook}} 🌿\n\n{{coreMessage}}\n\n회원 혜택이 생각보다 좋아요.\n링크 프로필에 있어요 👆`,
    tiktokTemplate: `[훅] {{hook}}\n\n[혜택1] {{supportPoint1}}\n[혜택2] {{supportPoint2}}\n\n[CTA] 지금 바로 회원 되기!`,
    openchatTemplate: `🎁 [회원 전용] {{productName}} 선공개\n\n안녕하세요, 산물입니다.\n\n{{hook}}\n\n📌 상품: {{productName}}\n📌 회원 혜택: {{supportPoint1}}\n📌 제한: {{supportPoint2}}\n\n⚠️ 회원 전용 링크로만 주문 가능합니다.\n🔗 {{cta}}: {{link}}\n\n항상 좋은 과일을 가장 먼저 드릴 수 있어서 감사합니다 🙏`,
    usageCount: 7,
  },
  {
    id: "t6",
    name: "시즌 마감형",
    type: "season_end",
    description: "시즌 막바지 상품 안내로 구매 긴급성 자극",
    purpose: "재고 소진, 희소성 강조",
    blogTemplate: `# {{hook}}\n\n{{coreMessage}}\n\n이번 시즌의 {{productName}}을 놓치지 마세요.\n\n{{supportPoint1}}\n{{supportPoint2}}\n{{supportPoint3}}\n\n{{cta}} → {{link}}`,
    instagramTemplate: `⏰ {{hook}}\n\n{{coreMessage}}\n\n🔴 {{supportPoint1}}\n🔴 {{supportPoint2}}\n🔴 {{supportPoint3}}\n\n{{cta}} 👇\n\n#시즌마감 #산물 #제철과일 #{{productName}}`,
    threadsTemplate: `{{hook}} ⏰\n\n{{coreMessage}}\n\n이번 기회 놓치면 내년까지 기다려야 해요.\n링크 프로필에 있어요 👆`,
    tiktokTemplate: `[긴급] {{hook}}\n\n[포인트1] {{supportPoint1}}\n[포인트2] {{supportPoint2}}\n\n[CTA] 지금 바로 주문하세요!`,
    openchatTemplate: `⏰ [긴급 안내] {{productName}} 시즌 마감\n\n산물 회원 여러분,\n{{hook}}\n\n📌 상품: {{productName}}\n📌 상황: {{coreMessage}}\n📌 수량: {{supportPoint1}}\n\n🔗 {{cta}}: {{link}}\n\n재고 소진 시 조기 마감됩니다 🙏`,
    usageCount: 4,
  },
  {
    id: "t7",
    name: "돌발특가형",
    type: "flash_offer",
    description: "예상치 못한 좋은 상품 입고 시 빠르게 알리는 템플릿",
    purpose: "긴급 판매, 회원 특전",
    blogTemplate: `# {{hook}}\n\n{{coreMessage}}\n\n{{supportPoint1}}\n{{supportPoint2}}\n{{supportPoint3}}\n\n{{cta}} → {{link}}`,
    instagramTemplate: `🚨 {{hook}}\n\n{{coreMessage}}\n\n⚡ {{supportPoint1}}\n⚡ {{supportPoint2}}\n⚡ {{supportPoint3}}\n\n{{cta}} 👇\n\n#돌발특가 #산물 #한정판매`,
    threadsTemplate: `{{hook}} 🚨\n\n{{coreMessage}}\n\n오늘만이에요. 링크 프로필에 있어요 👆`,
    tiktokTemplate: `[긴급] {{hook}}\n\n[특가] {{supportPoint1}}\n[한정] {{supportPoint2}}\n\n[CTA] 지금 바로!`,
    openchatTemplate: `🚨 [돌발특가] {{productName}} 한정 오픈\n\n산물 회원 여러분,\n{{hook}}\n\n📌 상품: {{productName}}\n📌 혜택: {{supportPoint1}}\n📌 기간: {{supportPoint2}}\n\n⚠️ 재고 한정, 조기 마감 가능\n🔗 {{cta}}: {{link}}`,
    usageCount: 6,
  },
  {
    id: "t8",
    name: "재구매 유도형",
    type: "repurchase",
    description: "기존 고객의 재구매를 유도하는 감사 콘텐츠",
    purpose: "고객 유지, 재구매율 향상",
    blogTemplate: `# {{hook}}\n\n{{coreMessage}}\n\n{{supportPoint1}}\n{{supportPoint2}}\n{{supportPoint3}}\n\n{{audience}}에게 특별히 추천드립니다.\n\n{{cta}} → {{link}}`,
    instagramTemplate: `💚 {{hook}}\n\n{{coreMessage}}\n\n✔️ {{supportPoint1}}\n✔️ {{supportPoint2}}\n✔️ {{supportPoint3}}\n\n{{cta}} 👇\n\n#산물 #재구매 #단골고객 #감사`,
    threadsTemplate: `{{hook}} 💚\n\n{{coreMessage}}\n\n다시 찾아와 주셔서 감사해요.\n링크 프로필에 있어요 👆`,
    tiktokTemplate: `[감사] {{hook}}\n\n[혜택1] {{supportPoint1}}\n[혜택2] {{supportPoint2}}\n\n[CTA] {{cta}}!`,
    openchatTemplate: `💚 [재구매 감사] {{productName}} 추천\n\n다시 찾아와 주신 회원 여러분께 감사드립니다.\n\n{{hook}}\n\n📌 추천 상품: {{productName}}\n📌 내용: {{coreMessage}}\n\n🔗 {{cta}}: {{link}}\n\n항상 좋은 과일로 보답하겠습니다 🙏`,
    usageCount: 2,
  },
];
